/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package func.ui;

import func.dao.OrderDAO;
import func.dao.TableDAO;
import func.entity.OrderEntity;
import func.entity.PaymentEntity;
import func.entity.TableEntity;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author quoca
 */
public class DialogQRThanhToan extends javax.swing.JDialog {

    String urlCheck = null;
    OrderEntity od = null;
    String tableId = null;

    /**
     * Creates new form JDialogQRThanhToan
     */
    public DialogQRThanhToan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public OrderEntity getOd() {
        return od;
    }

    public void setOd(OrderEntity od) {
        this.od = od;
        init(String.valueOf(od.getTotalPrice()));
    }

    public String getTableId() {
        return tableId;
    }

    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String callAPI(String amount) {
        try {
            // URL API backend
            URL url = new URL("http://localhost:3030/create-payment/");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();

            // Thiết lập phương thức POST
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setDoOutput(true);

            // Dữ liệu JSON gửi đi
            String jsonInputString = "{ \"amount\": " + amount + ", \"desc\": \"Do%an%tai%FuncDev\" }";

            // Ghi dữ liệu vào body request
            try (OutputStream os = conn.getOutputStream()) {
                byte[] input = jsonInputString.getBytes("utf-8");
                os.write(input, 0, input.length);
            }

            // Đọc phản hồi từ server
            int responseCode = conn.getResponseCode();
            System.out.println("Response Code: " + responseCode);

            if (responseCode == HttpURLConnection.HTTP_OK || responseCode == HttpURLConnection.HTTP_CREATED) {
                try (BufferedReader br = new BufferedReader(
                        new InputStreamReader(conn.getInputStream(), "utf-8"))) {
                    StringBuilder response = new StringBuilder();
                    String responseLine;
                    while ((responseLine = br.readLine()) != null) {
                        response.append(responseLine.trim());
                    }
                    return response.toString();
                }
            }

            conn.disconnect();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    void init(String amount) {
        setLocationRelativeTo(null);
        String url = callAPI(amount);
        System.out.println(url);
        if (url != null) {
            int lastSlashIndex = url.lastIndexOf("/");
            int queryIndex = url.indexOf("?");

            // Kiểm tra nếu có "/" và nó nằm sau "?" thì mới cắt
            if (lastSlashIndex != -1 && queryIndex != -1 && lastSlashIndex > queryIndex) {
                urlCheck = url.substring(lastSlashIndex + 1); // Lưu phần sau dấu "/"
                url = url.substring(0, lastSlashIndex); // Cắt bỏ phần sau dấu "/"
            } else {
                urlCheck = ""; // Gán giá trị mặc định nếu không tìm thấy "/"
            }
            try {
                URL urlImage = new URL(url.substring(0, lastSlashIndex));
                ImageIcon imgIcon = new ImageIcon(urlImage);
                jLabel1.setText("");
                jLabel1.setIcon(imgIcon);
                checkBank();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    String getAPI() {
        try {
            String url = "http://localhost:3030/get-payment/" + urlCheck; // URL API
            HttpURLConnection conn = (HttpURLConnection) new URL(url).openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/json"); // Đặt header

            if (conn.getResponseCode() != 200) {
                throw new RuntimeException("Failed : HTTP error code : " + conn.getResponseCode());
            }

            BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String output;
            StringBuilder response = new StringBuilder();
            while ((output = br.readLine()) != null) {
                response.append(output);
            }
            conn.disconnect();
            System.out.println("Response: " + response.toString()); // In kết quả
            return response.toString();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    void checkBank() {
        Timer timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (getAPI().equals("PAID")) {
                    ((Timer) e.getSource()).stop(); // Dừng timer khi điều kiện thỏa mãn
                    TableDAO tableDAO = new TableDAO();
                    new OrderDAO().update(od);
                    if (tableDAO.selectTableNumberByOrderId(String.valueOf(od.getOrderId())).size() > 1) {
                        for (String table : tableDAO.selectTableNumberByOrderId(String.valueOf(od.getOrderId()))) {
                            TableEntity tb = new TableEntity();
                            tb.setStatus("available");
                            tb.setTableId(Integer.parseInt(table));
                            tableDAO.updateTableStatus(tb);
                        }
                    }
                    dispose();
                }
            }
        });
        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogQRThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogQRThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogQRThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogQRThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogQRThanhToan dialog = new DialogQRThanhToan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
