/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package func.ui;

import func.application.MainForm;
import func.cell.ChinhSuaBang;
import func.cell.KetHopBang;
import func.cell.SuKienHanhDong;
import func.dao.OrderDAO;
import func.dao.OrderDetailsDAO;
import func.dao.TableDAO;
import func.dto.OrderDetailsDTO;
import func.entity.OrderDetailEntity;
import func.entity.OrderEntity;
import func.entity.TableEntity;
import func.utils.Message;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quoca
 */
public class DialogChiTietMonAn extends javax.swing.JDialog {

    String order;
    DefaultTableModel model;
    private String table;
    private MainForm mainForm;

    /**
     * Creates new form JDialogChiTietMonAn
     */
    public DialogChiTietMonAn(MainForm parent, boolean modal) {
        super(parent, modal);
        this.mainForm = parent;
        initComponents();
    }

    void init() {
        model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        int i = 1;
        tblDanhSach.getColumnModel().getColumn(4).setMinWidth(0);
        tblDanhSach.getColumnModel().getColumn(4).setMaxWidth(0);
        tblDanhSach.getColumnModel().getColumn(4).setWidth(0);
        List<OrderDetailsDTO> od = new OrderDetailsDAO().selectByIdOrder(order);
        for (OrderDetailsDTO order : od) {
            String status = "Đã hủy";
            switch (order.getStatus()) {
                case "pending":
                    status = "Đang chờ xác nhận";
                    break;
                case "cooking":
                    status = "Đang nấu";
                    break;
                case "ready":
                    status = "Đã nấu xong";
                    break;
            }
            model.addRow(new Object[]{
                i, order.getProductName(), status, "", order.getOrderDetailId()
            });
            i++;
        }
        SuKienHanhDong event = new SuKienHanhDong() {
            @Override
            public void Edit(int row) {
                Message.warning(null, "Chúng tôi chưa làm nút sửa. Mong quý khách thông cảm");
                return;
            }

            @Override
            public void Delete(int row) {
                String note = Message.input(null, "Lí do hủy đơn hàng");
                if (note.trim().isBlank()) {
                    Message.warning(null, "Bạn không thể để trống lí do");
                    return;
                }
                OrderDetailsDTO statusProduct = new OrderDetailsDAO().selectStatusProductById(String.valueOf(tblDanhSach.getValueAt(row, 4)));
                if (statusProduct.getStatus().equals("pending")) {
                    OrderDetailEntity od = new OrderDetailEntity();
                    od.setNote(note);
                    od.setStatus("canceled");
                    od.setOrderDetailId((int) tblDanhSach.getValueAt(row, 4));
                    new OrderDetailsDAO().updateStatusOrderDetails(od);
                    Message.info(null, "Món ăn đã được huỷ");
                    init();
                } else {
                    Message.warning(null, "Món đang được nấu hoặc đã hoàn thành. Không thể huỷ được!");
                    return;
                }
            }

            @Override
            public void View(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

        };

        tblDanhSach.getColumnModel().getColumn(3).setCellRenderer(new KetHopBang(false));
        tblDanhSach.getColumnModel().getColumn(3).setCellEditor(new ChinhSuaBang(false, event));
    }

    public String getOrder() {
        return order;
    }

    public void setOrder(String order) {
        this.order = order;
        init();
    }

    public String getTable() {
        return table;
    }

    public void setTable(String table) {
        this.table = table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(137, 137, 229));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi Tiết Món Ăn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên món ", "Trạng thái", "Hành động", "Id"
            }
        ));
        tblDanhSach.setRowHeight(40);
        tblDanhSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDanhSach);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Hủy hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<OrderDetailsDTO> od = new OrderDetailsDAO().selectByIdOrder(order);
        for (OrderDetailsDTO order : od) {
            if (!order.getStatus().equals("pending") && !order.getStatus().equals("canceled")) {
                Message.warning(null, "Bạn không thể huỷ đơn hàng khi có món đang được nấu và đã hoàn thành");
                return;
            }
        }
        String note = Message.input(null, "Nhập lí do bạn huỷ đơn hàng");
        if (note == null || note.isBlank()) {
            Message.warning(null, "Bạn chưa nhập lý do hủy đơn hàng!");
            return;
        }
        OrderEntity order = new OrderEntity();
        order.setStatus("canceled");
        order.setOrderId(Integer.parseInt(this.order));
        order.setNote(note);
        new OrderDAO().cancelOrder(order);
        TableDAO tableDAO = new TableDAO();
        if (tableDAO.selectTableNumberByOrderId(this.order).size() > 1) {
            for (String table : tableDAO.selectTableNumberByOrderId(this.order)) {
                TableEntity tb = new TableEntity();
                tb.setStatus("available");
                tb.setTableId(Integer.parseInt(table));
                tableDAO.updateTableStatus(tb);
            }
        } else {
            TableEntity tb = new TableEntity();
            tb.setStatus("available");
            tb.setTableId(Integer.parseInt(table));
            tableDAO.updateTableStatus(tb);
        }
        dispose();
        mainForm.showPanel(new PanelChonBan());

        Message.info(this, "Bạn đã huỷ hoá đơn thành công");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            MainForm mainForm = new MainForm(); // Khởi tạo MainForm
            mainForm.setVisible(true);

            // Sau khi MainForm chạy, mở JDialogChiTietMonAn với MainForm
            DialogChiTietMonAn dialog = new DialogChiTietMonAn(mainForm, true);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    // End of variables declaration//GEN-END:variables
}
