/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import func.cell.ChinhSuaBang;
import func.cell.KetHopBang;
import func.cell.PanelUD;
import func.cell.SuKienHanhDong;
import func.dao.CategoryDAO;
import func.entity.CategoriesEntity;
import func.utils.Message;
import java.util.List;
import javax.swing.table.DefaultTableModel;
// Tạo TableCellRenderer để thay đổi màu sắc
// import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ASUS
 */
public class PanelQuanLyDanhMuc extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyDanhMuc
     */
    DefaultTableModel model;
    CategoriesEntity category = null;
    List<CategoriesEntity> list = new CategoryDAO().selectAll();
    int categoryId;

    public PanelQuanLyDanhMuc() {
        initComponents();
        showTable();

        SuKienHanhDong event = new SuKienHanhDong() {

            @Override
            public void Edit(int row) {
                categoryId = list.get(row).getCategoryId();
                String tenDanhMuc = String.valueOf(tblDanhSach.getValueAt(row, 1));
                txtTenDanhMuc.setText(tenDanhMuc);
                String trangThai = String.valueOf(tblDanhSach.getValueAt(row, 2));
                if (trangThai.equals("Đang hoạt động")) {
                    cboTrangThai.setSelectedItem("Đang hoạt động");
                } else {
                    cboTrangThai.setSelectedItem("Không hoạt động");
                }
                btnThem.setText("Lưu danh mục");
            }

            @Override
            public void Delete(int row) {
                categoryId = list.get(row).getCategoryId();
                boolean confirm = Message.confirm(PanelQuanLyDanhMuc.this, "Bạn có chắc chắn muốn xóa danh mục này không ?");
                if (confirm) {
                    new CategoryDAO().delete(String.valueOf(categoryId));
                    showTable();
                    Message.info(PanelQuanLyDanhMuc.this, "Xóa danh mục thành công");

                } else {
                    Message.info(PanelQuanLyDanhMuc.this, "Hủy thao tác xóa danh mục.");
                }
                clearText();
                btnThem.setText("Thêm danh mục");
            }

            @Override
            public void View(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

        };

        tblDanhSach.getColumnModel().getColumn(3).setCellRenderer(new KetHopBang(false));
        tblDanhSach.getColumnModel().getColumn(3).setCellEditor(new ChinhSuaBang(false,event));
    }

    void clearText() {
        txtTenDanhMuc.setText("");
        cboTrangThai.setSelectedIndex(0);
    }

    public void showTable() {
        List<CategoriesEntity> list = new CategoryDAO().selectAll(); // Cập nhật lại danh sách 
        model = (DefaultTableModel) this.tblDanhSach.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng

        int number = 1;

        for (CategoriesEntity category : list) {
            String name = category.getCategoryName();
            String trangThai = category.isIsActive() ? "Đang hoạt động" : "Không hoạt động";

            // Thêm số thứ tự tự động vào bảng
            model.addRow(new Object[]{
                number++, name, trangThai
            });
        }

//        tblDanhSach.getColumnModel().getColumn(2).setCellRenderer(new StatusCellRenderer());
    }

//    // Tạo một lớp TableCellRenderer để thay đổi màu sắc cột trạng thái
//    public class StatusCellRenderer extends JLabel implements TableCellRenderer {
//
//        @Override
//        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
//            setText(value.toString()); // Đặt giá trị cho ô
//
//            // Kiểm tra trạng thái và thay đổi màu sắc cho phù hợp
//            if ("Hoạt động".equals(value)) {
//                setForeground(Color.GREEN); // Màu xanh lá cây
//            } else if ("Không hoạt động".equals(value)) {
//                setForeground(Color.RED); // Màu đỏ
//            }
//            return this;
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenDanhMuc = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH DANH MỤC");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Trạng thái hoạt động");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tên danh mục");

        txtTenDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDanhMucActionPerformed(evt);
            }
        });

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Không hoạt động" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboTrangThai, 0, 352, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUẢN LÝ DANH MỤC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnThem.setBackground(new java.awt.Color(102, 102, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm danh mục");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên danh mục", "Trạng thái hoạt động", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setRowHeight(40);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(224, 224, 224))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDanhMucActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        // trim() : Phương thức này sẽ loại bỏ tất cả các khoảng trắng (dấu cách) ở đầu và chuỗi cuối. Điều này đảm bảo rằng nếu người dùng vô tình nhập thêm khoảng trắng ở đầu hoặc cuối, chúng sẽ không gây ra lỗi khi lưu vào cơ sở dữ liệu hoặc khi xử lý.
        String categoryName = txtTenDanhMuc.getText().trim();
        boolean isActive = cboTrangThai.getSelectedItem().equals("Đang hoạt động");

        if (categoryName.isEmpty()) {
            Message.warning(this, "Tên danh mục không được để trống.");
            return;
        }

        CategoriesEntity category = new CategoriesEntity();

        if (btnThem.getText().equals("Thêm danh mục")) {
            category.setCategoryName(categoryName);
            category.setIsActive(isActive);
            boolean confirm = Message.confirm(PanelQuanLyDanhMuc.this, "Bạn có chắc chắn muốn thêm danh mục này không ?");
            if (confirm) {
                new CategoryDAO().insert(category);
                Message.info(this, "Thêm danh mục thành công");
            } else {
                Message.info(this, "Hủy thao tác thêm danh mục.");
            }
        } else if (btnThem.getText().equals("Lưu danh mục")) {
            category.setCategoryId(categoryId);
            category.setCategoryName(categoryName);
            category.setIsActive(isActive);
            boolean confirm = Message.confirm(PanelQuanLyDanhMuc.this, "Bạn có chắc chắn muốn sửa danh mục này không ?");
            if (confirm) {
                new CategoryDAO().update(category);
                Message.info(this, "Sửa danh mục thành công");
            } else {
                Message.info(this, "Hủy thao tác sửa danh mục.");
            }
            btnThem.setText("Thêm danh mục");
        }
        clearText();
        showTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked

    }//GEN-LAST:event_tblDanhSachMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtTenDanhMuc;
    // End of variables declaration//GEN-END:variables
}
