/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import func.dao.ThongKeDAO;
import func.dto.ProductStatistics;
import func.utils.Currency;
import func.utils.Message;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartMouseEvent;
import org.jfree.chart.ChartMouseListener;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.CategoryItemEntity;
import org.jfree.chart.entity.ChartEntity;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author quoctris.dev
 */
public class PanelThongKe extends javax.swing.JPanel {

    List<ProductStatistics> lsThongKeMonAn;
    DefaultTableModel model;

    /**
     * Creates new form PanelThongKe
     */
    public PanelThongKe() {
        initComponents();
        hienThiBieuDo();
        Date now = new Date();
        selectDate.setDate(now);
        selectDate.setDateFormatString("dd/MM/yyyy");
        model = (DefaultTableModel) tblDanhSach.getModel();
        selectDate.setMaxSelectableDate(new Date());
        LocalDate currentDate = LocalDate.now();

        int ngay = currentDate.getDayOfMonth();
        int thang = currentDate.getMonthValue();
        int nam = currentDate.getYear();
        lsThongKeMonAn = ThongKeDAO.thongKeMonAn("Ngày", ngay, thang, nam);
        fillTable();
        showPieChartInPanel(lsThongKeMonAn, pnMonAn);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cboThongKe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnDoanhThu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        pnMonAn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cboChonThongKe = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        selectDate = new com.toedter.calendar.JDateChooser();
        selectYear = new com.toedter.calendar.JYearChooser();
        btnConfirm = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        cboThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tuần", "Tháng", "Năm" }));
        cboThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThongKeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ DOANH THU");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Thống kế theo:");

        javax.swing.GroupLayout pnDoanhThuLayout = new javax.swing.GroupLayout(pnDoanhThu);
        pnDoanhThu.setLayout(pnDoanhThuLayout);
        pnDoanhThuLayout.setHorizontalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnDoanhThuLayout.setVerticalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cboThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thống kê doanh thu", jPanel1);

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setRowHeight(40);
        tblDanhSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pnMonAnLayout = new javax.swing.GroupLayout(pnMonAn);
        pnMonAn.setLayout(pnMonAnLayout);
        pnMonAnLayout.setHorizontalGroup(
            pnMonAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnMonAnLayout.setVerticalGroup(
            pnMonAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Thống kế theo:");

        cboChonThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tháng", "Năm" }));
        cboChonThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboChonThongKeMouseClicked(evt);
            }
        });
        cboChonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChonThongKeActionPerformed(evt);
            }
        });

        jPanel6.setLayout(new java.awt.CardLayout());
        jPanel6.add(selectDate, "card3");
        jPanel6.add(selectYear, "card2");

        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboChonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnConfirm)
                        .addContainerGap(450, Short.MAX_VALUE))
                    .addComponent(pnMonAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cboChonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addComponent(pnMonAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("THỐNG KÊ MÓN ĂN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thống kê món ăn", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThongKeActionPerformed
        // TODO add your handling code here:
        hienThiBieuDo();
    }//GEN-LAST:event_cboThongKeActionPerformed

    void hideSelect() {
        selectDate.setVisible(false);
        selectYear.setVisible(false);

    }
    private void cboChonThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboChonThongKeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboChonThongKeMouseClicked

    private void cboChonThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChonThongKeActionPerformed
        // TODO add your handling code here:
        String luaChon = String.valueOf(cboChonThongKe.getSelectedItem());

        // Đầu tiên: ẩn hết tất cả
        hideSelect();
        // Hiện theo lựa chọn
        switch (luaChon) {
            case "Ngày":
                hideSelect();
                selectDate.setVisible(true);
                break;
            case "Năm":
                hideSelect();
                selectYear.setVisible(true);
                break;
        }
    }//GEN-LAST:event_cboChonThongKeActionPerformed
    void fillTable() {
        model.setRowCount(0);
        for (ProductStatistics pd : lsThongKeMonAn) {
            model.addRow(new Object[]{pd.getProductName(), pd.getQuantity(), Currency.formatVND(pd.getTotal())});
        }
    }

    public void showPieChartInPanel(List<ProductStatistics> list, JPanel pnlBieuDo) {
        if (lsThongKeMonAn.size() == 0) {
            model.setRowCount(0);
            pnMonAn.removeAll();
            pnMonAn.repaint();
            Message.warning(null, "Hôm nay chưa bán được món nào");
            return;
        }
        pnlBieuDo.removeAll(); // Xoá nội dung cũ

        DefaultPieDataset dataset = new DefaultPieDataset();
        for (ProductStatistics ps : list) {
            dataset.setValue(ps.getProductName(), ps.getQuantity());
        }

        JFreeChart chart = ChartFactory.createPieChart(
                "Top 5 sản phẩm bán chạy",
                dataset,
                true, false, false
        );

        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0} ({2})"));
        plot.setBackgroundPaint(Color.WHITE);
        plot.setOutlineVisible(false);

        // Bảng màu đẹp cho tối đa 5 phần
        Color[] colors = {
            new Color(102, 204, 255),
            new Color(255, 153, 102),
            new Color(153, 255, 153),
            new Color(255, 102, 178),
            new Color(255, 255, 102),};

        int i = 0;
        for (Object key : dataset.getKeys()) {
            plot.setSectionPaint((Comparable) key, colors[i % colors.length]); // vòng lặp nếu ít hơn hoặc bằng 5
            i++;
        }

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(671, 532));
        chartPanel.setMouseWheelEnabled(true);

        pnlBieuDo.setLayout(new java.awt.BorderLayout());
        pnlBieuDo.add(chartPanel, java.awt.BorderLayout.CENTER);
        pnlBieuDo.validate();
        pnlBieuDo.repaint();
    }
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String luaChon = String.valueOf(cboChonThongKe.getSelectedItem());
        Date date = selectDate.getDate();
        LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        int ngay = 0, thang = 0, nam = 0;
        switch (luaChon) {
            case "Ngày":
                ngay = localDate.getDayOfMonth();
                thang = localDate.getMonthValue();
                nam = localDate.getYear();
                break;
            case "Tháng":
                thang = localDate.getMonthValue();
                nam = localDate.getYear();
                break;
            case "Năm":
                nam = selectYear.getYear();
                break;
        }

        lsThongKeMonAn = ThongKeDAO.thongKeMonAn(luaChon, ngay, thang, nam);
        if (lsThongKeMonAn.size() == 0) {
            model.setRowCount(0);
            pnMonAn.removeAll();
            pnMonAn.repaint();
            Message.warning(null, "Vui lòng chọn thời gian khác. Do thời gian này không thể thống kê món ăn được");
            return;
        }
        fillTable();
        showPieChartInPanel(lsThongKeMonAn, pnMonAn);
    }//GEN-LAST:event_btnConfirmActionPerformed
    private void hienThiBieuDo() {
        String luaChon = (String) cboThongKe.getSelectedItem();

        // Lấy dữ liệu dựa trên lựa chọn
        CategoryDataset dataset = switch (luaChon) {
            case "Ngày" ->
                ThongKeDAO.getRevenueDataset("day");
            case "Tuần" ->
                ThongKeDAO.getRevenueDataset("week");
            case "Tháng" ->
                ThongKeDAO.getRevenueDataset("month");
            default ->
                ThongKeDAO.getRevenueDataset("year");
        };

        // Tạo biểu đồ
        JFreeChart chart = ChartFactory.createBarChart(
                "Thống kê doanh thu",
                luaChon, "Doanh thu (VNĐ)", dataset
        );

        // Tuỳ chỉnh biểu đồ
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.GRAY);
        plot.setOutlineVisible(false);

        // Tuỳ chỉnh thanh Bar
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        for (int i = 0; i < dataset.getRowCount(); i++) {
            String rowKey = (String) dataset.getRowKey(i);
            if (rowKey.equals("Đơn hoàn thành")) {
                renderer.setSeriesPaint(i, new Color(52, 152, 219)); // Xanh - Hoàn thành
            } else if (rowKey.equals("Đơn bị huỷ")) {
                renderer.setSeriesPaint(i, new Color(231, 76, 60));  // Đỏ - Bị huỷ
            }
        }
        renderer.setBarPainter(new StandardBarPainter());

        // Tạo ChartPanel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(981, 409));
        chartPanel.addChartMouseListener(new ChartMouseListener() {
            @Override
            public void chartMouseClicked(ChartMouseEvent event) {
                ChartEntity entity = event.getEntity();
                if (entity instanceof CategoryItemEntity categoryEntity) {
                    String selectedDate = categoryEntity.getColumnKey().toString();

                    // Xác định kiểu thống kê
                    String luaChon = (String) cboThongKe.getSelectedItem();
                    String type = switch (luaChon) {
                        case "Ngày" ->
                            "day";
                        case "Tuần" ->
                            "week";
                        case "Tháng" ->
                            "month";
                        default ->
                            "year";
                    };

                    // Hiển thị lựa chọn biểu đồ khi chọn "Ngày"
                    if (type.equals("day")) {
                        String[] options = {"Phương thức thanh toán trong ngày", "Xem doanh thu theo ca"};
                        int choice = JOptionPane.showOptionDialog(
                                SwingUtilities.getWindowAncestor(chartPanel),
                                "Chọn loại biểu đồ bạn muốn hiển thị",
                                "Chọn biểu đồ",
                                JOptionPane.DEFAULT_OPTION,
                                JOptionPane.QUESTION_MESSAGE,
                                null,
                                options,
                                options[0]
                        );

                        if (choice == 0) {
                            hienThiPieChart(selectedDate, type);
                        } else if (choice == 1) {
                            hienThiBieuDoTheoCa(selectedDate);
                        }
                    } else {
                        System.out.println(selectedDate);
                        hienThiPieChart(selectedDate, type);
                    }
                }
            }

            @Override
            public void chartMouseMoved(ChartMouseEvent event) {
            }
        });

        // Hiển thị biểu đồ
        pnDoanhThu.removeAll();
        pnDoanhThu.setLayout(new BorderLayout());
        pnDoanhThu.add(chartPanel, BorderLayout.CENTER);
        pnDoanhThu.revalidate();
        pnDoanhThu.repaint();
    }

    private void hienThiPieChart(String selectedDate, String type) {
        DefaultPieDataset dataset = ThongKeDAO.getRevenueByPaymentMethod(selectedDate, type);

        if (dataset.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để hiển thị biểu đồ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFreeChart pieChart = ChartFactory.createPieChart(
                "Phương thức thanh toán - " + selectedDate,
                dataset, true, true, false);

        PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setOutlineVisible(false);

        // Gán màu cho từng phần tử dựa trên loại thanh toán
        for (Object obj : dataset.getKeys()) {
            Comparable<?> key = (Comparable<?>) obj;
            String label = key.toString();  // Lấy nhãn
            if (label.startsWith("Tiền mặt (Hoàn thành)")) {
                plot.setSectionPaint(label, new Color(46, 204, 113));  // Xanh lá
            } else if (label.startsWith("QR-Code (Hoàn thành)")) {
                plot.setSectionPaint(label, new Color(241, 196, 15));  // Vàng
            } else if (label.startsWith("QR-Code (Đơn huỷ)")) {
                plot.setSectionPaint(label, new Color(231, 76, 60));  // Đỏ
            } else {
                plot.setSectionPaint(label, new Color(52, 152, 219));  // Màu xanh dương mặc định
            }
        }

        ChartPanel pieChartPanel = new ChartPanel(pieChart);
        pieChartPanel.setPreferredSize(new Dimension(500, 400));

        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Thống kê phương thức thanh toán", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(pieChartPanel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    private void hienThiBieuDoTheoCa(String date) {
        CategoryDataset dataset = ThongKeDAO.getRevenueByShift(date);

        JFreeChart chart = ChartFactory.createBarChart(
                "Thống kê doanh thu theo ca làm (" + date + ")",
                "Ca làm", "Giá trị", dataset
        );

        // Tuỳ chỉnh biểu đồ
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.GRAY);
        plot.setOutlineVisible(false);

        // Tuỳ chỉnh thanh Bar
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        for (int i = 0; i < dataset.getRowCount(); i++) {
            String rowKey = dataset.getRowKey(i).toString().trim(); // Đảm bảo không có khoảng trắng thừa

            if (rowKey.equalsIgnoreCase("Doanh thu")) {
                renderer.setSeriesPaint(i, new Color(52, 152, 219)); // Xanh - Doanh thu
            } else if (rowKey.equalsIgnoreCase("Đơn bị huỷ")) {
                renderer.setSeriesPaint(i, new Color(231, 76, 60));  // Đỏ - Đơn bị hủy
            }
        }
        renderer.setBarPainter(new StandardBarPainter());

        // Hiển thị biểu đồ trong popup
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Chi tiết doanh thu theo ca", true);
        dialog.setSize(600, 400);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());
        dialog.add(new ChartPanel(chart), BorderLayout.CENTER);
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cboChonThongKe;
    private javax.swing.JComboBox<String> cboThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnDoanhThu;
    private javax.swing.JPanel pnMonAn;
    private com.toedter.calendar.JDateChooser selectDate;
    private com.toedter.calendar.JYearChooser selectYear;
    private javax.swing.JTable tblDanhSach;
    // End of variables declaration//GEN-END:variables
}
