/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import func.cell.ChinhSuaBang;
import func.cell.KetHopBang;
import func.cell.SuKienHanhDong;
import func.dao.BillDAO;
import func.dto.BillDTO;
import func.utils.Currency;
import func.utils.Message;
import java.awt.Frame;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quoctris.dev
 */
public class PanelHoaDon extends javax.swing.JPanel {

    List<BillDTO> ls;
    DefaultTableModel model;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM HH:mm");

    /**
     * Creates new form PanelHoaDon
     */
    public PanelHoaDon() {
        initComponents();
        init();
    }

    void init() {
        model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        int i = 1;
        ls = new BillDAO().selectAll();
        for (BillDTO bill : ls) {
            LocalDateTime time = bill.getOrderDate().toLocalDateTime();
            model.addRow(new Object[]{
                i, bill.getCustomerName() == null ? "Khách vãng lai" : bill.getCustomerName(), bill.getCustomerPhone() == null ? "Không có" : bill.getCustomerPhone(), bill.getNumberTable(), Currency.formatVND(bill.getTotal_price()), bill.getStatus(), time.format(formatter)});
            i++;
        }
        SuKienHanhDong event = new SuKienHanhDong() {
            @Override
            public void Edit(int row) {
                Message.warning(null, "Chưa có tính năng");
                return;
            }

            @Override
            public void Delete(int row) {
                Message.warning(null, "Chưa có tính năng");
                return;
            }

            @Override
            public void View(int row) {
                DialogChiTietHoaDon donHang = new DialogChiTietHoaDon((Frame) SwingUtilities.getWindowAncestor(PanelHoaDon.this), true);
                donHang.setBill(ls.get(row));
                donHang.setVisible(true);
            }

        };

        tblDanhSach.getColumnModel().getColumn(7).setCellRenderer(new KetHopBang(true));
        tblDanhSach.getColumnModel().getColumn(7).setCellEditor(new ChinhSuaBang(true, event));
        tblDanhSach.getColumnModel().getColumn(7).setMinWidth(95);
        tblDanhSach.getColumnModel().getColumn(7).setMaxWidth(95);
        tblDanhSach.getColumnModel().getColumn(7).setWidth(95);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên khách", "Số điện thoại", "Số bàn", "Tổng tiền", "Trạng thái", "Thời gian", "Hành động"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setRowHeight(40);
        tblDanhSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(2).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(3).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(4).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(5).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(6).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    // End of variables declaration//GEN-END:variables
}
