/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import func.cell.ChinhSuaBang;
import func.cell.KetHopBang;
import func.cell.SuKienHanhDong;
import func.dao.BillDAO;
import func.dto.BillDTO;
import func.utils.Currency;
import func.utils.Message;
import java.awt.Frame;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quoctris.dev
 */
public class PanelHoaDon extends javax.swing.JPanel {

    List<BillDTO> ls = new ArrayList<>();
    private int currentPage = 1;
    private int rowsPerPage = 16;
    private int totalPages = 1;
    DefaultTableModel model;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM HH:mm");

    /**
     * Creates new form PanelHoaDon
     */
    public PanelHoaDon() {
        initComponents();
        init();
    }

    void init() {
        fillTable();
        SuKienHanhDong event = new SuKienHanhDong() {
            @Override
            public void Edit(int row) {
                Message.warning(null, "Chưa có tính năng");
                return;
            }

            @Override
            public void Delete(int row) {
                Message.warning(null, "Chưa có tính năng");
                return;
            }

            @Override
            public void View(int row) {
                DialogChiTietHoaDon donHang = new DialogChiTietHoaDon((Frame) SwingUtilities.getWindowAncestor(PanelHoaDon.this), true);
                donHang.setBill(ls.get(row));
                donHang.setVisible(true);
            }

        };

        tblDanhSach.getColumnModel().getColumn(7).setCellRenderer(new KetHopBang(true));
        tblDanhSach.getColumnModel().getColumn(7).setCellEditor(new ChinhSuaBang(true, event));
        tblDanhSach.getColumnModel().getColumn(7).setMinWidth(95);
        tblDanhSach.getColumnModel().getColumn(7).setMaxWidth(95);
        tblDanhSach.getColumnModel().getColumn(7).setWidth(95);
    }

    void fillTable() {
        ls = new BillDAO().selectAll(); // Lấy toàn bộ danh sách hóa đơn
        totalPages = (int) Math.ceil((double) ls.size() / rowsPerPage);
        currentPage = 1;
        showBillPage(currentPage);
    }

    private void showBillPage(int page) {
        model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);

        int start = (page - 1) * rowsPerPage;
        int end = Math.min(start + rowsPerPage, ls.size());

        for (int i = start; i < end; i++) {
            BillDTO bill = ls.get(i);
            LocalDateTime time = bill.getOrderDate().toLocalDateTime();

            model.addRow(new Object[]{
                i + 1,
                bill.getCustomerName() == null ? "Khách vãng lai" : bill.getCustomerName(),
                bill.getCustomerPhone() == null ? "Không có" : bill.getCustomerPhone(),
                bill.getNumberTable(),
                Currency.formatVND(bill.getTotal_price()),
                bill.getStatus(),
                time.format(formatter)
            });
        }

        // Gợi ý cập nhật thông tin phân trang
        jLabel3.setText("Trang " + currentPage + "/" + totalPages);
    }

    private void nextPage() {
        if (currentPage < totalPages) {
            currentPage++;
            showBillPage(currentPage);
        }
    }

    private void previousPage() {
        if (currentPage > 1) {
            currentPage--;
            showBillPage(currentPage);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên khách", "Số điện thoại", "Số bàn", "Tổng tiền", "Trạng thái", "Thời gian", "Hành động"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setRowHeight(40);
        tblDanhSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(2).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(3).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(4).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(5).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(6).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(137, 137, 229));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("HÓA ĐƠN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jButton3.setText(">|");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("|<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jLabel3))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        nextPage();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        previousPage();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    // End of variables declaration//GEN-END:variables
}
