/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

/**
 *
 * @author HOANG NHI
 */
public class PanelCauHinhMayIn extends javax.swing.JPanel {

    /**
     * Creates new form PanelCauHinhMayIn
     */
    public PanelCauHinhMayIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdoMay1 = new javax.swing.JRadioButton();
        rdoMay2 = new javax.swing.JRadioButton();
        rdoMay3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdoMacDinh1 = new javax.swing.JRadioButton();
        rdoMacDinh3 = new javax.swing.JRadioButton();
        rdoMacDinh2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtKNThanhCong = new javax.swing.JLabel();
        txtNgoaiTuyen = new javax.swing.JLabel();
        txtLoi = new javax.swing.JLabel();
        btnThemMayIn = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setBackground(new java.awt.Color(153, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cấu hình máy in");

        rdoMay1.setText("Máy in 1");
        rdoMay1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdoMay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMay1ActionPerformed(evt);
            }
        });

        rdoMay2.setText("Máy in 2");
        rdoMay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMay2ActionPerformed(evt);
            }
        });

        rdoMay3.setText("Máy in 3");
        rdoMay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMay3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Chọn máy in");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Máy in mặc định");

        rdoMacDinh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMacDinh1ActionPerformed(evt);
            }
        });

        rdoMacDinh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMacDinh3ActionPerformed(evt);
            }
        });

        rdoMacDinh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMacDinh2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Trạng thái máy in");

        txtKNThanhCong.setText("Kết nối thành công");

        txtNgoaiTuyen.setText("Máy in ngoại tuyến");

        txtLoi.setText("Lỗi máy in");

        btnThemMayIn.setText("Thêm máy in");
        btnThemMayIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMayInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoMay3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoMay1)
                                    .addComponent(rdoMay2))
                                .addGap(230, 230, 230)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoMacDinh3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLoi)
                                        .addGap(22, 22, 22))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoMacDinh2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNgoaiTuyen))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoMacDinh1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtKNThanhCong)))))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnThemMayIn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoMay1)
                            .addComponent(txtKNThanhCong)))
                    .addComponent(rdoMacDinh1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoMay2)
                        .addGap(18, 18, 18)
                        .addComponent(rdoMay3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdoMacDinh2)
                            .addComponent(txtNgoaiTuyen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoMacDinh3)
                            .addComponent(txtLoi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnThemMayIn)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdoMay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMay1ActionPerformed

    private void rdoMacDinh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMacDinh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMacDinh1ActionPerformed

    private void rdoMay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMay2ActionPerformed

    private void rdoMay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMay3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMay3ActionPerformed

    private void rdoMacDinh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMacDinh3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMacDinh3ActionPerformed

    private void rdoMacDinh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMacDinh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMacDinh2ActionPerformed

    private void btnThemMayInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMayInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemMayInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemMayIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdoMacDinh1;
    private javax.swing.JRadioButton rdoMacDinh2;
    private javax.swing.JRadioButton rdoMacDinh3;
    private javax.swing.JRadioButton rdoMay1;
    private javax.swing.JRadioButton rdoMay2;
    private javax.swing.JRadioButton rdoMay3;
    private javax.swing.JLabel txtKNThanhCong;
    private javax.swing.JLabel txtLoi;
    private javax.swing.JLabel txtNgoaiTuyen;
    // End of variables declaration//GEN-END:variables
}
