/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import func.dao.OrderOrderDetailDAO;
import func.dto.OrderOrderDetailDTO;
import func.utils.StatusConverter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author This PC
 */
public class PanelDanhSachDonHang extends javax.swing.JPanel {

    /**
     * Creates new form DanhSachDonHangForm
     */
    public PanelDanhSachDonHang() {
        initComponents();
        init();
        refreshTable();
    }
    
    void init() {
        lblBan.setText("");
        lblKhuVuc.setText("");
        lblThoiGian.setText("");
        lblThuNgan.setText("");
        DefaultTableModel model = (DefaultTableModel) tableDanhSach.getModel();
        model.setRowCount(0);
        List<OrderOrderDetailDTO> orders = OrderOrderDetailDAO.loadAllOrdersToTable();
        for (OrderOrderDetailDTO order : orders) {
            String trangThai;
            switch (order.getStatus()) {
                case "pending":
                    trangThai = "Đang Chờ";
                    break;
                case "processing":
                    trangThai = "Đang Xử Lý";
                    break;
                case "cooking":
                    trangThai = "Đang Chế Biến";
                    break;
                case "completed":
                    trangThai = "Đã Hoàn Thành";
                    break;
                case "canceled":
                    trangThai = "Hủy";
                    break;
                default:
                    trangThai = "Không Xác Định";
                    break;
                
            }
            
            model.addRow(new Object[]{
                order.getOrderId(),
                order.getOrderDate(),
                order.getCashierName(),
                order.getZone(),
                order.getTableNumber(),
                trangThai,
                order.getNote()
            });
        }
        
    }
    
    void refreshTable() {
        Timer time = new Timer(10000, new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                init();
            }
        }
        );
        time.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDanhSach = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        btnXemChiTiet = new javax.swing.JButton();
        lblBan = new javax.swing.JLabel();
        lblThoiGian = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblThuNgan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblKhuVuc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        tableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã tham chiếu", "Thời gian", "Thu ngân", "Khu Vực", "Bàn", "Trạng thái", "Ghi Chú"
            }
        ));
        tableDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDanhSach);

        jLabel2.setText("Chi Tiết Đơn Hàng");

        jLabel3.setText("Thời Gian :");

        jLabel6.setText("Bàn :");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang Xử Lý", "Đang Chế Biến", "Đã Hoàn Thành", "Đang Chờ", "Huỷ" }));

        jLabel7.setText("Trạng Thái  :");

        jLabel8.setText("Số Lượng : ");

        jLabel10.setText("Ghi Chú");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane2.setViewportView(txtNote);

        jButton5.setText("Lưu Thay Đổi ");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnXemChiTiet.setText("Xem Món");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        lblBan.setText("jLabel4");

        lblThoiGian.setText("jLabel4");

        jLabel4.setText("Thu Ngân :");

        lblThuNgan.setText("jLabel5");

        jLabel5.setText("Khu Vực :");

        lblKhuVuc.setText("jLabel9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblThoiGian))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblBan)))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblThuNgan)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKhuVuc))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(133, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblThoiGian))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblThuNgan)
                            .addComponent(jLabel5)
                            .addComponent(lblKhuVuc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(btnXemChiTiet)
                            .addComponent(lblBan))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jButton5)
                            .addComponent(jLabel7)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐƠN HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            int orderId = Integer.parseInt(txtTimKiem.getText());
            OrderOrderDetailDAO.loadOrderDetailsToTable(tableDanhSach, orderId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        if (maThamChieu == 0) {
            System.out.println(maThamChieu);
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn hàng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        PanelDanhSachMonAn dialog = new PanelDanhSachMonAn((javax.swing.JFrame) SwingUtilities.getWindowAncestor(this), true, maThamChieu);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnXemChiTietActionPerformed
    private int maThamChieu;
    private void tableDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDanhSachMouseClicked
        
        int selectedRow = tableDanhSach.getSelectedRow(); // Lấy hàng được chọn
        if (selectedRow >= 0) {
            try {
                // Lấy giá trị từ bảng, kiểm tra null trước khi dùng
                Object orderIdObj = tableDanhSach.getValueAt(selectedRow, 0);
                Object orderDateObj = tableDanhSach.getValueAt(selectedRow, 1);
                Object cashierNameObj = tableDanhSach.getValueAt(selectedRow, 2);
                Object zoneObj = tableDanhSach.getValueAt(selectedRow, 3);
                Object tableNumberObj = tableDanhSach.getValueAt(selectedRow, 4);
                Object statusObj = tableDanhSach.getValueAt(selectedRow, 5);
                Object noteObj = tableDanhSach.getValueAt(selectedRow, 6);

                // Chuyển đổi giá trị sang kiểu phù hợp
                int orderId = 0;
                if (orderIdObj instanceof Integer) {
                    orderId = (Integer) orderIdObj;
                } else if (orderIdObj instanceof String) {
                    orderId = Integer.parseInt((String) orderIdObj);
                }
                
                String orderDate = (orderDateObj != null) ? orderDateObj.toString() : "";
                String cashierName = (cashierNameObj != null) ? cashierNameObj.toString() : "";
                String zone = (zoneObj != null) ? zoneObj.toString() : "";
                String tableNumber = (tableNumberObj != null) ? tableNumberObj.toString() : "";
                String status = (statusObj != null) ? statusObj.toString() : "";
                String note = (noteObj != null) ? noteObj.toString() : "";

                // Chuyển trạng thái sang tiếng Việt
                status = StatusConverter.convertStatus(status);
                String Status;
                switch (status) {
                    case "pending":
                        Status = "Đang Chờ";
                        break;
                    case "processing":
                        Status = "Đang Xử Lý";
                        break;
                    case "cooking":
                        Status = "Đang Chế Biến";
                        break;
                    case "completed":
                        Status = "Đã Hoàn Thành";
                        break;
                    case "canceled":
                        Status = "Hủy";
                        break;
                    default:
                        Status = "Không Xác Định";
                        break;
                    
                }
                maThamChieu = orderId;
                // Hiển thị dữ liệu lên giao diện
                lblKhuVuc.setText(zone);
                lblThoiGian.setText(orderDate);
                lblThuNgan.setText(cashierName);
                lblBan.setText(tableNumber);
                txtNote.setText(note);
                cboTrangThai.setSelectedItem(Status);
            } catch (NumberFormatException e) {
                System.err.println("Lỗi chuyển đổi số: " + e.getMessage());
            } catch (Exception e) {
                System.err.println("Lỗi xử lý dữ liệu: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_tableDanhSachMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblKhuVuc;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblThuNgan;
    private javax.swing.JTable tableDanhSach;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
