/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import func.dao.ThongKeDAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartMouseEvent;
import org.jfree.chart.ChartMouseListener;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.CategoryItemEntity;
import org.jfree.chart.entity.ChartEntity;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author quoctris.dev
 */
public class PanelThongKe extends javax.swing.JPanel {

    /**
     * Creates new form PanelThongKe
     */
    public PanelThongKe() {
        initComponents();
        hienThiBieuDo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cboThongKe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnDoanhThu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        cboThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tuần", "Tháng", "Năm" }));
        cboThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThongKeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ DOANH THU");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Kiểu thống kê:");

        javax.swing.GroupLayout pnDoanhThuLayout = new javax.swing.GroupLayout(pnDoanhThu);
        pnDoanhThu.setLayout(pnDoanhThuLayout);
        pnDoanhThuLayout.setHorizontalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnDoanhThuLayout.setVerticalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cboThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thống kê doanh thu", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống kê món ăn", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThongKeActionPerformed
        // TODO add your handling code here:
        hienThiBieuDo();
    }//GEN-LAST:event_cboThongKeActionPerformed
    private void hienThiBieuDo() {
        String luaChon = (String) cboThongKe.getSelectedItem();

        // Lấy dữ liệu dựa trên lựa chọn
        CategoryDataset dataset = switch (luaChon) {
            case "Ngày" ->
                ThongKeDAO.getRevenueDataset("day");
            case "Tuần" ->
                ThongKeDAO.getRevenueDataset("week");
            case "Tháng" ->
                ThongKeDAO.getRevenueDataset("month");
            default ->
                ThongKeDAO.getRevenueDataset("year");
        };

        // Tạo biểu đồ
        JFreeChart chart = ChartFactory.createBarChart(
                "Thống kê doanh thu",
                luaChon, "Doanh thu (VNĐ)", dataset
        );

        // Tuỳ chỉnh biểu đồ
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.GRAY);
        plot.setOutlineVisible(false);

        // Tuỳ chỉnh thanh Bar
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new Color(52, 152, 219));
        renderer.setBarPainter(new StandardBarPainter());

        // Tạo ChartPanel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(981, 409));
        chartPanel.addChartMouseListener(new ChartMouseListener() {
            @Override
            public void chartMouseClicked(ChartMouseEvent event) {
                ChartEntity entity = event.getEntity();
                if (entity instanceof CategoryItemEntity categoryEntity) {
                    String selectedDate = categoryEntity.getColumnKey().toString();

                    // Xác định kiểu thống kê
                    String luaChon = (String) cboThongKe.getSelectedItem();
                    String type = switch (luaChon) {
                        case "Ngày" ->
                            "day";
                        case "Tuần" ->
                            "week";
                        case "Tháng" ->
                            "month";
                        default ->
                            "year";
                    };

                    // Hiển thị lựa chọn biểu đồ khi chọn "Ngày"
                    if (type.equals("day")) {
                        String[] options = {"Phương thức thanh toán trong ngày", "Xem doanh thu theo ca"};
                        int choice = JOptionPane.showOptionDialog(
                                SwingUtilities.getWindowAncestor(chartPanel),
                                "Chọn loại biểu đồ bạn muốn hiển thị",
                                "Chọn biểu đồ",
                                JOptionPane.DEFAULT_OPTION,
                                JOptionPane.QUESTION_MESSAGE,
                                null,
                                options,
                                options[0]
                        );

                        if (choice == 0) {
                            hienThiPieChart(selectedDate, type);
                        } else if (choice == 1) {
                            hienThiBieuDoTheoCa(selectedDate);
                        }
                    } else {
                        System.out.println(selectedDate);
                        hienThiPieChart(selectedDate, type);
                    }
                }
            }

            @Override
            public void chartMouseMoved(ChartMouseEvent event) {
            }
        });

        // Hiển thị biểu đồ
        pnDoanhThu.removeAll();
        pnDoanhThu.setLayout(new BorderLayout());
        pnDoanhThu.add(chartPanel, BorderLayout.CENTER);
        pnDoanhThu.revalidate();
        pnDoanhThu.repaint();
    }

    private void hienThiPieChart(String selectedDate, String type) {
        DefaultPieDataset dataset = ThongKeDAO.getRevenueByPaymentMethod(selectedDate, type);

        JFreeChart pieChart = ChartFactory.createPieChart(
                "Phương thức thanh toán - " + selectedDate,
                dataset, true, true, false);
        PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setSectionPaint("Tiền mặt", new Color(46, 204, 113));  // Xanh lá
        plot.setSectionPaint("QR-Code", new Color(231, 76, 60));  // Đỏ
        plot.setBackgroundPaint(Color.WHITE);
        plot.setOutlineVisible(false);
        if (dataset.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để hiển thị biểu đồ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return; // Thoát nếu không có dữ liệu
        }
        ChartPanel pieChartPanel = new ChartPanel(pieChart);
        pieChartPanel.setPreferredSize(new Dimension(500, 400));

        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Thống kê phương thức thanh toán", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(pieChartPanel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    private void hienThiBieuDoTheoCa(String date) {
        CategoryDataset dataset = ThongKeDAO.getRevenueByShift(date);

        JFreeChart chart = ChartFactory.createBarChart(
                "Thống kê doanh thu theo ca làm (" + date + ")",
                "Ca làm", "Doanh thu (VNĐ)", dataset
        );
// Tuỳ chỉnh biểu đồ
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.GRAY);
        plot.setOutlineVisible(false);
        // Tuỳ chỉnh thanh Bar
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new Color(52, 152, 219));
        renderer.setBarPainter(new StandardBarPainter());
        // Hiển thị biểu đồ trong popup
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Chi tiết doanh thu theo ca", true);
        dialog.setSize(600, 400);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());
        dialog.add(new ChartPanel(chart), BorderLayout.CENTER);
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnDoanhThu;
    // End of variables declaration//GEN-END:variables
}
