/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import func.cell.ChinhSuaBang;
import func.cell.KetHopBang;
import func.cell.SuKienHanhDong;
import func.dao.OrderOrderDetailDAO;
import func.dto.OrderOrderDetailDTO;
import func.utils.Message;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quoctris.dev
 */
public class PanelDonHang extends javax.swing.JPanel {

    DefaultTableModel model;
    private List<OrderOrderDetailDTO> ls = new ArrayList<>();
    private int currentPage = 1;
    private int rowsPerPage = 14;
    private int totalPages = 1;

    /**
     * Creates new form PanelDonHang
     */
    public PanelDonHang() {
        initComponents();
        init();
    }

    void init() {

        SuKienHanhDong event = new SuKienHanhDong() {
            @Override
            public void Edit(int row) {
                DialogSuaDonHang donHang = new DialogSuaDonHang((Frame) SwingUtilities.getWindowAncestor(PanelDonHang.this), true);
                donHang.setOrderDetail(ls.get(row));
                donHang.setVisible(true);
                init();
            }

            @Override
            public void Delete(int row) {
                String note = Message.input(null, "Lí do huỷ món");
                if (note == null || note.trim().isEmpty()) {
                    Message.warning(null, "Vui lòng nhập lý do huỷ món!");
                    return;
                }
                OrderOrderDetailDTO canceledOrder = new OrderOrderDetailDTO();
                canceledOrder.setStatus("canceled");
                canceledOrder.setOrderDetailId(ls.get(row).getOrderDetailId());
                OrderOrderDetailDAO.updateStatusById(canceledOrder, note);
                init();
            }

            @Override
            public void View(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

        };

        tblDanhSach.getColumnModel().getColumn(6).setCellRenderer(new KetHopBang(false));
        tblDanhSach.getColumnModel().getColumn(6).setCellEditor(new ChinhSuaBang(false, event));
        setSizeTable();
    }

    void fillTable() {
        ls = OrderOrderDetailDAO.selectAllInDay();
        totalPages = (int) Math.ceil((double) ls.size() / rowsPerPage);
        currentPage = 1;
        showCookPage(currentPage);
    }

    private void showCookPage(int page) {
        model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);

        int start = (page - 1) * rowsPerPage;
        int end = Math.min(start + rowsPerPage, ls.size());

        for (int i = start; i < end; i++) {
            OrderOrderDetailDTO od = ls.get(i);
            String statusText = od.getStatus().equals("cooking") ? "Đang nấu" : "Đang chờ";

            model.addRow(new Object[]{
                i + 1,
                od.getProductName(),
                od.getTableName(),
                od.getZoneName(),
                od.getCreatedAt(),
                statusText
            });
        }

        // Hiển thị thông tin trang nếu cần
        jLabel3.setText("Trang " + currentPage + "/" + totalPages);
    }

    private void nextPage() {
        if (currentPage < totalPages) {
            currentPage++;
            showCookPage(currentPage);
        }
    }

    private void previousPage() {
        if (currentPage > 1) {
            currentPage--;
            showCookPage(currentPage);
        }
    }

    void setSizeTable() {
        tblDanhSach.getColumnModel().getColumn(0).setMinWidth(35);
        tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(35);
        tblDanhSach.getColumnModel().getColumn(0).setWidth(25);
        tblDanhSach.getColumnModel().getColumn(0).setMinWidth(160);
        tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(160);
        tblDanhSach.getColumnModel().getColumn(0).setWidth(160);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(137, 137, 229));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ĐƠN HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Món ăn", "Số bàn", "Khu vực", "Thời gian", "Trạng thái", "Hành động"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setRowHeight(40);
        tblDanhSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSach.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton4.setText(">|");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("|<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jLabel3))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        nextPage();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        previousPage();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    // End of variables declaration//GEN-END:variables
}
