/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package func.ui;

import func.application.MainForm;
import func.dao.MergeTableDAO;
import func.dao.OrderDAO;
import func.dao.TableDAO;
import func.entity.MergeTableEntity;
import func.entity.OrderEntity;
import func.entity.TableEntity;
import func.utils.Auth;
import func.utils.Message;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author quoctris.dev
 */
public class PanelChonBan extends javax.swing.JPanel {

    private List<String> zone;
    private List<TableEntity> table;

    /**
     * Creates new form JDialogChonBan
     */
    public PanelChonBan() {
        initComponents();
        selectZone();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnZone = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnKhuVuc = new javax.swing.JPanel();
        pnBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHỌN BÀN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnZone.setBorder(javax.swing.BorderFactory.createTitledBorder("Khu vực"));

        pnKhuVuc.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(pnKhuVuc);

        javax.swing.GroupLayout pnZoneLayout = new javax.swing.GroupLayout(pnZone);
        pnZone.setLayout(pnZoneLayout);
        pnZoneLayout.setHorizontalGroup(
            pnZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnZoneLayout.setVerticalGroup(
            pnZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pnBan.setBorder(javax.swing.BorderFactory.createTitledBorder("Bàn"));
        pnBan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Vui lòng chọn khu vực");
        pnBan.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBan, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void selectZone() {
        zone = new TableDAO().selectZone();
        pnKhuVuc.removeAll();
        pnKhuVuc.updateUI();
        int i = 0;
        for (String zone : zone) {
            JButton jButtonCategory = new JButton();
            jButtonCategory.setText(String.valueOf(zone));
            jButtonCategory.setPreferredSize(new java.awt.Dimension(100, 44));
            jButtonCategory.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Ví dụ: Hiển thị danh sách món theo danh mục
                    selectTableById(zone);
                }
            });
            jButtonCategory.setMargin(new java.awt.Insets(2, 2, 2, 2));
            jButtonCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButtonCategory.setFont(new java.awt.Font("Segoe UI", 0, 10));
            i++;
            pnKhuVuc.add(jButtonCategory);
        }

        pnKhuVuc.setLayout(new java.awt.GridLayout(i, 0));
    }

    public void selectTableById(String id) {

        table = new TableDAO().selectByZone(id);
        pnBan.removeAll();
        pnBan.updateUI();
        JPanel panelRecipe = new JPanel(new java.awt.GridLayout(0, 4, 10, 5));
        JScrollPane mainScrollPane = new JScrollPane();

        for (TableEntity tb : table) {
            String status = tb.getStatus();
            String color;
            switch (status) {
                case "available":
                    status = "Bàn đang trống";
                    color = "green";
                    break;
                case "occupied":
                    status = "Bàn đang có người sử dụng";
                    color = "yellow";
                    break;
                case "reserved":
                    status = "Bàn đã đặt trước";
                    color = "orange";
                    break;
                case "waiting_payment":
                    status = "Bàn đang chờ thanh toán";
                    color = "blue";
                    break;
                case "cleaning":
                    status = "Bàn đang dọn dẹp";
                    color = "purple";
                    break;
                case "maintenance":
                    status = "Bàn đang được bảo trì";
                    color = "red";
                    break;
                default:
                    Message.warning(this, "Bàn không được xác định");
                    color = "gray"; // Màu mặc định nếu trạng thái không hợp lệ
            }

            JButton jButtonRecipe = new JButton();
            jButtonRecipe.setText(String.valueOf(tb.getTableNumber()));
            jButtonRecipe.setPreferredSize(new java.awt.Dimension(110, 110));

//            if (displayPicture(menu) == null) {
//            } else {
//                jButtonRecipe.setIcon(displayPicture(menu));
//            }
//            jButtonRecipe.setBackground(new Color(192,192,192));
            jButtonRecipe.setText("<html><body style=\"text-align:center; padding:5px; margin:0;"
                    + "border-radius:10px; border: 2px solid " + color + "; box-shadow: 2px 2px 5px rgba(0,0,0,0.2);\">"
                    + "<p style=\"font-size: 14px; font-weight: bold; color:black; margin:5px 0;\">"
                    + "BÀN " + tb.getTableNumber() + "</p>"
                    + "<p style=\"font-size: 13px; font-weight: bold; color:" + color + "; margin:5px 0;\">"
                    + status + "</p>"
                    + "</body></html>");
            jButtonRecipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jButtonRecipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jButtonRecipe.setMargin(new java.awt.Insets(2, 2, 2, 2));
            jButtonRecipe.addActionListener(e -> handleTableClick(tb));
            jButtonRecipe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            panelRecipe.add(jButtonRecipe);

            mainScrollPane.setViewportView(panelRecipe);

            pnBan.add(mainScrollPane, java.awt.BorderLayout.CENTER);
            pnBan.validate();
            pnBan.validate();
        }
//        disableSideButton();
    }

    private void handleTableClick(TableEntity table) {
        int existingOrderId = new MergeTableDAO().getActiveOrderIdByTable(table.getTableId());
        if (existingOrderId > 0) {
            MainForm mainForm = (MainForm) SwingUtilities.getWindowAncestor(this);
            PanelTaoDon orderPanel = new PanelTaoDon();
            orderPanel.setTable(table.getTableNumber());
            orderPanel.setTable(String.valueOf(table.getTableId()));
            orderPanel.setOrder(String.valueOf(existingOrderId));
            mainForm.showPanel(orderPanel);
            return;
        } else {
            boolean saveCustomerInfo = Message.confirm(this, "Khách hàng muốn lưu thông tin không?");
            String customerName = "", phoneNumber = "";

            if (saveCustomerInfo) {
                JDialogThongTinKhachHang customerInfoDialog = new JDialogThongTinKhachHang(
                        (Frame) SwingUtilities.getWindowAncestor(this), true);
                customerInfoDialog.setVisible(true);
                customerName = customerInfoDialog.getTenKhach();
                phoneNumber = customerInfoDialog.getSoDienThoai();
            }

            createOrderForTable(table, customerName, phoneNumber);
        }
    }

    private void createOrderForTable(TableEntity table, String customerName, String phoneNumber) {
        MergeTableDAO mergeTableDAO = new MergeTableDAO();
        int existingOrderId = mergeTableDAO.getActiveOrderIdByTable(table.getTableId());

        MainForm mainForm = (MainForm) SwingUtilities.getWindowAncestor(this);
        PanelTaoDon orderPanel = new PanelTaoDon();
        orderPanel.setTable(table.getTableNumber());
        orderPanel.setTable(String.valueOf(table.getTableId()));

        if (existingOrderId > 0) {
            orderPanel.setOrder(String.valueOf(existingOrderId));
            mainForm.showPanel(orderPanel);
            return;
        }

        if (!"available".equals(table.getStatus())) {
            Message.warning(this, "Bàn đang được sử dụng hoặc đã đặt trước!");
            return;
        }

        boolean confirmCreateOrder = Message.confirm(this, "Bạn có muốn tạo Order mới cho bàn " + table.getTableNumber() + "?");
        if (!confirmCreateOrder) {
            return;
        }

        int newOrderId = createNewOrder(customerName, phoneNumber);
        if (newOrderId <= 0) {
            Message.error(this, "Lỗi khi tạo Order!");
            return;
        }

        linkOrderToTable(newOrderId, table);
        orderPanel.setOrder(String.valueOf(newOrderId));
        mainForm.showPanel(orderPanel);
    }

    private int createNewOrder(String customerName, String phoneNumber) {
        OrderEntity order = new OrderEntity();
        order.setCashierId(Auth.user.getUserId());
        order.setStatus("processing");
        order.setCustomerName(customerName);
        order.setCustomerPhone(phoneNumber);
        return new OrderDAO().createOrder(order);
    }

    private void linkOrderToTable(int orderId, TableEntity table) {
        MergeTableEntity mergeTable = new MergeTableEntity();
        mergeTable.setOrderId(orderId);
        mergeTable.setTableId(table.getTableId());
        new MergeTableDAO().insertMergeTable(mergeTable);

        table.setStatus("occupied");
        new TableDAO().updateTableStatus(table);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnBan;
    private javax.swing.JPanel pnKhuVuc;
    private javax.swing.JPanel pnZone;
    // End of variables declaration//GEN-END:variables
}
